name: Crypto Alert Bot
# NOTE: All cron schedules use UTC timezone (MYT = UTC+8)
# This runs every hour at xx:30 from 07:30 to 23:30 MYT

on:
  schedule:
    - cron: "30 23-15 * * *"   # every hour at xx:30 (UTC) / 07:30–23:30 MYT
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install numpy==1.26.4
          pip install pandas==2.2.2
          pip install pandas_ta==0.3.14b0
          pip install requests

      - name: Run bot
        run: python crypto_alert_bot.py
