name: Crypto Alert Bot

on:
  schedule:
    - cron: "30 23,1,3,5,7,9,11,13,15 * * *"  # MYT 07:30..23:30
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    env:
      TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install pandas pandas_ta requests

      - name: Run bot
        run: python crypto_alert_bot.py
